"""bloques por seccion y traslapes por hora

Revision ID: 15a59a2897d4
Revises: 
Create Date: 2026-09-21 12:05:03.187346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15a59a2897d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carrera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('ciclo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('docente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grado_academico', sa.String(length=50), nullable=True),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('correo', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('ciclo_carrera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ciclo', sa.Integer(), nullable=False),
    sa.Column('id_carrera', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_carrera'], ['carrera.id'], ),
    sa.ForeignKeyConstraint(['id_ciclo'], ['ciclo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('id_carrera', sa.Integer(), nullable=False),
    sa.Column('semestre', sa.Integer(), nullable=False),
    sa.Column('no_periodos_semanales', sa.Integer(), nullable=False),
    sa.Column('duracion_bloque', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_carrera'], ['carrera.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_carrera', sa.Integer(), nullable=False),
    sa.Column('semestre', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['id_carrera'], ['carrera.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bloque_horario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_seccion', sa.Integer(), nullable=False),
    sa.Column('dia', sa.Integer(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('tipo', sa.Enum('clase', 'receso'), nullable=False),
    sa.ForeignKeyConstraint(['id_seccion'], ['seccion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asignacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ciclo', sa.Integer(), nullable=False),
    sa.Column('id_seccion', sa.Integer(), nullable=False),
    sa.Column('id_curso', sa.Integer(), nullable=False),
    sa.Column('id_docente', sa.Integer(), nullable=True),
    sa.Column('id_bloque', sa.Integer(), nullable=False),
    sa.Column('modalidad', sa.Enum('presencial', 'virtual'), nullable=True),
    sa.ForeignKeyConstraint(['id_bloque'], ['bloque_horario.id'], ),
    sa.ForeignKeyConstraint(['id_ciclo'], ['ciclo.id'], ),
    sa.ForeignKeyConstraint(['id_curso'], ['curso.id'], ),
    sa.ForeignKeyConstraint(['id_docente'], ['docente.id'], ),
    sa.ForeignKeyConstraint(['id_seccion'], ['seccion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asignacion')
    op.drop_table('bloque_horario')
    op.drop_table('seccion')
    op.drop_table('curso')
    op.drop_table('ciclo_carrera')
    op.drop_table('docente')
    op.drop_table('ciclo')
    op.drop_table('carrera')
    # ### end Alembic commands ###
